import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { providers, Contract } from 'ethers'
import Web3Modal from "web3modal"
import { useEffect, useRef, useState } from 'react'

export default function Home() {
  const [walletConnected, setWalletConnected] = useState(false);
  const [loading, setLoading] = useState(false);
  const web3ModalRef = useRef();

  const getProviderOrSigner = async (needSigner = false) => {
    const provider = await web3ModalRef.current.connect();
    const web3Provider = new providers.Web3Provider(provider);

    const { chainId } = await web3Provider.getNetwork();
    if (chainId !== 80001) {
      window.alert('Change the network to Mumbai');
      throw new Error('Change network to Mumbai');
    }
    
    if (needSigner) {
      const signer = web3Provider.getSigner();
      return signer;
    }
    return web3Provider;
  };

  const connectWallet = async () => {
    try {
      await getProviderOrSigner();
      setWalletConnected(true);
    } catch (err) {
      console.error(err)
    }
  };

  const renderButton = () => {
    if (walletConnected) {
      return (
        <div class={styles.description}>
          Ready Playa 1 ?
        </div>
      );
    } else if (loading) {
      return <button class={styles.button}>Shuffling..</button>
    } else {
      return ( 
        <button onClick={connectWallet} class= "inline-block text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-black hover:bg-white mt-4 lg:mt-0">
          Connect your wallet
        </button>
      )
    }
  }

  useEffect(() => {
    if (!walletConnected) {
      web3ModalRef.current = new Web3Modal({
        network: "mumbai",
        providerOptions: {},
        disableInjectedProvider: false,
      });
      connectWallet();
    }
  }, [walletConnected]);



  return (
    <div class="p-0">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div class="p-0">
      <div class= "p-0">
        <div class="p-0">
          <ul>
            <li>
              <Link href="/">
                <a>Home</a>
              </Link>
            </li>
            <li>
              <Link href="/cards">
                <a>Cards</a>
            </Link>
            </li>
            <li>
              <Link href="/numbers">
                <a>Numbers</a>
            </Link>
            </li>
          </ul>
        </div>
      </div>
      <div>
        <h1>Welcome to Plusheaven</h1>
      </div>
      <div>{renderButton()}</div>
      
    </div>   
      

      
    </div>
  )
}
